"""create all tables

Revision ID: 92b2b88ac0ef
Revises: 
Create Date: 2026-04-20 04:49:05.334168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92b2b88ac0ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_latitude', sa.Float(), nullable=False),
    sa.Column('max_latitude', sa.Float(), nullable=False),
    sa.Column('min_longitude', sa.Float(), nullable=False),
    sa.Column('max_longitude', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('customer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_customer_profile_phone_number'), 'customer_profile', ['phone_number'], unique=False)
    op.create_index(op.f('ix_customer_profile_region_id'), 'customer_profile', ['region_id'], unique=False)
    op.create_index(op.f('ix_customer_profile_user_id'), 'customer_profile', ['user_id'], unique=True)
    op.create_table('delivery_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('slot_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('order_cutoff_minutes', sa.Integer(), nullable=False),
    sa.Column('edit_cancel_lock_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'start_time', 'end_time', name='uq_slot_region_time_window'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_delivery_slot_region_id'), 'delivery_slot', ['region_id'], unique=False)
    op.create_table('driver_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('national_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bike_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_driver_profile_license_number'), 'driver_profile', ['license_number'], unique=False)
    op.create_index(op.f('ix_driver_profile_national_id_number'), 'driver_profile', ['national_id_number'], unique=False)
    op.create_index(op.f('ix_driver_profile_phone_number'), 'driver_profile', ['phone_number'], unique=False)
    op.create_index(op.f('ix_driver_profile_user_id'), 'driver_profile', ['user_id'], unique=True)
    op.create_table('grocery_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_grocery_item_name'), 'grocery_item', ['name'], unique=False)
    op.create_index(op.f('ix_grocery_item_region_id'), 'grocery_item', ['region_id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_index(op.f('ix_item_user_id'), 'item', ['user_id'], unique=False)
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('menu_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=False)
    op.create_index(op.f('ix_restaurant_region_id'), 'restaurant', ['region_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('driver_profile_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('restaurant_order_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('additional_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('placed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profile.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['delivery_slot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_driver_profile_id'), 'order', ['driver_profile_id'], unique=False)
    op.create_index(op.f('ix_order_region_id'), 'order', ['region_id'], unique=False)
    op.create_index(op.f('ix_order_restaurant_id'), 'order', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_order_slot_id'), 'order', ['slot_id'], unique=False)
    op.create_table('recurring_order_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('includes_restaurant', sa.Boolean(), nullable=False),
    sa.Column('grocery_payload', sa.JSON(), nullable=True),
    sa.Column('restaurant_order_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('additional_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_generated_for_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['delivery_slot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_recurring_order_template_customer_id'), 'recurring_order_template', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recurring_order_template_region_id'), 'recurring_order_template', ['region_id'], unique=False)
    op.create_index(op.f('ix_recurring_order_template_restaurant_id'), 'recurring_order_template', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_recurring_order_template_slot_id'), 'recurring_order_template', ['slot_id'], unique=False)
    op.create_table('region_driver_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('driver_profile_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profile.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'driver_profile_id', name='uq_region_driver_assignment'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_region_driver_assignment_driver_profile_id'), 'region_driver_assignment', ['driver_profile_id'], unique=False)
    op.create_index(op.f('ix_region_driver_assignment_region_id'), 'region_driver_assignment', ['region_id'], unique=False)
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('driver_profile_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('resolution_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profile.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_complaint_customer_id'), 'complaint', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaint_driver_profile_id'), 'complaint', ['driver_profile_id'], unique=False)
    op.create_index(op.f('ix_complaint_order_id'), 'complaint', ['order_id'], unique=False)
    op.create_index(op.f('ix_complaint_region_id'), 'complaint', ['region_id'], unique=False)
    op.create_table('driver_ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('driver_profile_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), server_default='payable', nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profile.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_driver_ledger_entry_driver_profile_id'), 'driver_ledger_entry', ['driver_profile_id'], unique=False)
    op.create_index(op.f('ix_driver_ledger_entry_order_id'), 'driver_ledger_entry', ['order_id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('grocery_item_id', sa.Integer(), nullable=True),
    sa.Column('item_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['grocery_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_order_item_grocery_item_id'), 'order_item', ['grocery_item_id'], unique=False)
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_table('proof_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_driver_profile_id', sa.Integer(), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_driver_profile_id'], ['driver_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_proof_attachment_order_id'), 'proof_attachment', ['order_id'], unique=False)
    op.create_index(op.f('ix_proof_attachment_uploaded_by_driver_profile_id'), 'proof_attachment', ['uploaded_by_driver_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proof_attachment_uploaded_by_driver_profile_id'), table_name='proof_attachment')
    op.drop_index(op.f('ix_proof_attachment_order_id'), table_name='proof_attachment')
    op.drop_table('proof_attachment')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_grocery_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_driver_ledger_entry_order_id'), table_name='driver_ledger_entry')
    op.drop_index(op.f('ix_driver_ledger_entry_driver_profile_id'), table_name='driver_ledger_entry')
    op.drop_table('driver_ledger_entry')
    op.drop_index(op.f('ix_complaint_region_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_order_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_driver_profile_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_customer_id'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_index(op.f('ix_region_driver_assignment_region_id'), table_name='region_driver_assignment')
    op.drop_index(op.f('ix_region_driver_assignment_driver_profile_id'), table_name='region_driver_assignment')
    op.drop_table('region_driver_assignment')
    op.drop_index(op.f('ix_recurring_order_template_slot_id'), table_name='recurring_order_template')
    op.drop_index(op.f('ix_recurring_order_template_restaurant_id'), table_name='recurring_order_template')
    op.drop_index(op.f('ix_recurring_order_template_region_id'), table_name='recurring_order_template')
    op.drop_index(op.f('ix_recurring_order_template_customer_id'), table_name='recurring_order_template')
    op.drop_table('recurring_order_template')
    op.drop_index(op.f('ix_order_slot_id'), table_name='order')
    op.drop_index(op.f('ix_order_restaurant_id'), table_name='order')
    op.drop_index(op.f('ix_order_region_id'), table_name='order')
    op.drop_index(op.f('ix_order_driver_profile_id'), table_name='order')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_restaurant_region_id'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_item_user_id'), table_name='item')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_grocery_item_region_id'), table_name='grocery_item')
    op.drop_index(op.f('ix_grocery_item_name'), table_name='grocery_item')
    op.drop_table('grocery_item')
    op.drop_index(op.f('ix_driver_profile_user_id'), table_name='driver_profile')
    op.drop_index(op.f('ix_driver_profile_phone_number'), table_name='driver_profile')
    op.drop_index(op.f('ix_driver_profile_national_id_number'), table_name='driver_profile')
    op.drop_index(op.f('ix_driver_profile_license_number'), table_name='driver_profile')
    op.drop_table('driver_profile')
    op.drop_index(op.f('ix_delivery_slot_region_id'), table_name='delivery_slot')
    op.drop_table('delivery_slot')
    op.drop_index(op.f('ix_customer_profile_user_id'), table_name='customer_profile')
    op.drop_index(op.f('ix_customer_profile_region_id'), table_name='customer_profile')
    op.drop_index(op.f('ix_customer_profile_phone_number'), table_name='customer_profile')
    op.drop_table('customer_profile')
    op.drop_table('user')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_table('region')
    # ### end Alembic commands ###

